### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by mweth** [olm3ca/mirror#1]
This is a nice summary.  I also have the [LM40SAMFHD700AG25WV Panel](https://www.panelook.com/LM40SAMFHD700AG25WV-40-TFT-Liquid-Crystal-Display-module-with-LED-Backlight-unit-detail_155306.html).  

From reviewing your outline, am I correct that you need a total of three things:
1. Replacement TV mainboard (with LVDS Cable, Ribbon Cables, Power Switch Board and IR Remote if possible)
2.  Scalar board
3.  Optional output device to provide familiar interface (like a Pi) to the mainboard.

If so, can you elaborate on the scaler board component needed?

**Comment by mweth** [comment]
And a followup.  Am I just confusing the term mainboard with scalar board?
Also, would this work for the Samsung model?  https://www.ebay.com/itm/126199255216  T.V53.03 Universal LCD TV Controller Driver Board V53 analog TV motherboard-ls

**Comment by olm3ca** [comment]
Glad you found this useful. Just to clarify - my panel is a [BOE DV430FHM-NN5](https://www.panelook.com/DV430FHM-NN5_BOE_43_LCM_overview_48245.html), **not** the one you linked to. I don't actually know what mainboard works with that panel, it's one question I have for other Mirror owners. On reddit, u/NuQ was really helpful to me in identifying what mainboard would work with my BOE panel, perhaps they can help you too. 

You only need two items. The scalar board of the Mirror remains and helps to power the backlight of the panel. 

1. A compatible TV mainboard that works with your panel (with all cables as you mentioned)
2. Output device like a pi, computer, or something else to display on the Mirror's panel (with the option to rotate 90 degrees). From my research, a chromecast, Fire stick and Apple TV lack the ability to rotate for a vertical display). 

Hope this helps!

**Comment by olm3ca** [comment]
> And a followup. Am I just confusing the term mainboard with scalar board? Also, would this work for the Samsung model? https://www.ebay.com/itm/126199255216 T.V53.03 Universal LCD TV Controller Driver Board V53 analog TV motherboard-ls

I actually purchased that but it would have required re-wiring the LVDS pins to match the panel, and that particular programmable mainboard didn't have documentation to show which pins go where. I don't think it's a viable option until someone can determine the pin layout.

**Comment by grhill424** [comment]
I found this link on reddit. It is beyond my technical ability, however, it may be useful to someone on here.
https://mega.nz/file/Ry01QICB#ISVMWEnbBoIZUlzqIjXKdnL-ZcMQZ-g6N9teqLYcc4k

I am interested because I have the samsung display and would like to be able to convert it.

**Comment by olm3ca** [comment]
Right, that file linked above is already in this repo in the datasheets folder. I compiled ideas from that reddit thread into [this set of "in progress" instructions](https://github.com/olm3ca/mirror/blob/main/Other%20models.md), which a Samsung panel user would need to develop further.

**Comment by olm3ca** [comment]
@mweth - just making sure you're aware a solution for your board has been found: https://github.com/olm3ca/mirror/issues/8 

I'll add this to the instructions, but good for you to know.
