### ISSUE TITLE
What is the CPU on the mirror

### ISSUE THREAD

**Issue by maco2035** [olm3ca/mirror#13]
Hey!

I am looking into buying a mirror. I wanted to see if it uses an AMLogic chip. This would help to try to keep the same original board, and just do some software magic to it. I would rather not open one, as my luck is I will need to buy 2 of them.

Thanks!

**Comment by olm3ca** [comment]
I honestly don't know. I never used the onboard system, just replaced it with a Vizio board. Good luck and hope you can crack it.
