### ISSUE TITLE
Update article and link for controller on eBay

### ISSUE THREAD

**Issue by avitascmor** [olm3ca/mirror#20]
@olm3ca can you please update the text in the article or remove the link for the controller as I put up an affiliate link without marking it as such and am being hounded to remove or update it.
<img width="917" alt="image" src="https://github.com/user-attachments/assets/b40c17d6-1362-41c1-922d-a8d483754760">

Thanks

**Comment by olm3ca** [comment]
I just updated the link to be the regular ebay listing, not an affiliate link. Can you confirm?

**Comment by avitascmor** [comment]
I think you updated in the lower section of the document but one link remains here:


This model requires a specific cable and controller:
https://ebay.us/HkicYV
Again thank you for updating, sorry for being a PITA.

Chris
________________________________

**Comment by olm3ca** [comment]
I found one other reference. If you still see it somewhere let me know.

**Comment by avitascmor** [comment]
Perfect, thank you!
________________________________
