### ISSUE TITLE
Finding the right parts for screen controller board

### ISSUE THREAD

**Issue by ffzero58** [olm3ca/mirror#21]
It has been a challenge to find a board that comes with the proper LVDS cable, power and IR wires/control. I've looked specifically for HV430FHB-N10 but they only come with the board and nothing else. I believe it requires a 51 pin LVDS cable. Where can I find the specific LVDS, power and IR components? Thanks.

**Comment by olm3ca** [comment]
Try looking for parts for the Vizio TV itself, not just the main board. [Here's the LVDS cable, for example](https://www.ebay.com/itm/363378193536?_skw=Vizio+D43fx-F4&epid=24041231835&itmmeta=01JCAZBHNC1S1PWYHNQWZJTDZE&hash=item549b073480:g:sA8AAOSwH8Ngiyhe&itmprp=enc%3AAQAJAAAA0HoV3kP08IDx%2BKZ9MfhVJKlQfAQ%2FXGD2OKnKldCuUf6Tbh52A%2BW61iidFmXrPClwHH1PErdMtxVLYtgyEQBrDrVdK518hKqZ%2FOgsk28pRnrSawZnUVKuW7YqvTdg96HfGaVNgJ4xLDunE0Yd4FvhcFwPGlYRMBaalYA4sp%2FpSTyRg%2BzcqrpLw%2BqL7MRUw6%2B8Sa9Du7CdxfkK%2FjDk9TWDiUo3zeqHolJgWIWwjYYOuSgvZ4pkAy6wsDblGP2Yn4jtOJpTz1O5VYblns7V5iWWw9E%3D%7Ctkp%3ABk9SR-Sart_iZA)
