### ISSUE TITLE
Mirror WiFi Server

### ISSUE THREAD

**Issue by jmbherbert** [olm3ca/mirror#7]
So I discovered while playing with the new mirror that the mirror WiFi network is actually running a dhcp server, and will hand out ip addresses to things that connect to it.

I then ran nmap on it, and it has some ports open (I forget which ones - I think 8080 for example)

Not super relevant for those of us who've modded it with a new TV board, but I am curious whether there might be any path here to root it in some way?

**Comment by olm3ca** [comment]
It would be really fun if we could jailbreak that scalar board somehow. Another person connected USB to it and it shows up in ADB. But to unlock the bootloader, we would need someone with experience with how to do that. 

The ideal solution for most people would be a simple USB jailbreak (without even opening the Mirror), then root Android and run apps on it...
